name: AlmaLinux-10
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['almalinux-10.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: almalinux-10
      vm_id: 1017
    secrets:
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
