name: Debian-13
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['debian-13.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: debian-13
      vm_id: 1020
    secrets:
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
