name: Talos
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['talos-1.12.pkrvars.hcl']
jobs:
  build:
    uses: ./.github/workflows/packer.yml
    with:
      name: talos-1.12
      vm_id: 1012
    secrets:
      netbird_setup_key: ${{ secrets.NETBIRD_SETUP_KEY }}
      proxmox_host: ${{ secrets.proxmox_host }}
      proxmox_user: ${{ secrets.proxmox_user }}
      proxmox_password: ${{ secrets.proxmox_password }}
